"""mkboot.py — the TinyPulse boot ROM: a UART bootloader, and the Verilog for it.

Hold ui_in[7] HIGH while reset is released and the core starts here, at
0x4000_0000, instead of at flash address 0. This program:

    1. sends "TP>" on the UART, meaning "ready, send me a program"
    2. reads a 4-byte little-endian length N
    3. reads N bytes and stores them to RAM A from 0x1000_0000 upwards
    4. sends back one byte, the sum of all N bytes mod 256, then 'K'
    5. waits for 'K' to finish transmitting, then jumps to 0x1000_0000

The UART runs at whatever UART_DIV holds: 434 after reset, which is
115,200 baud at 50 MHz. The loaded program runs from RAM, so it is lost at
power-off. For a program that survives, flash it with the Tiny Tapeout flasher.

Link programs for 0x1000_0000 (sw/link_ram.ld) and send them with
sw/tpload.py. User code can also re-enter the bootloader at any time by
jumping to 0x4000_0000, the way reset_usb_boot() does on an RP2040.

Run:  python3 sw/mkboot.py   (from the repo root) — regenerates
      src/boot/tp_bootrom.sv and prints the annotated listing.
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from mkprog import addi, lui, sw, lw, bne, jal, I, R, S, B, OPC_OPIMM, OPC_OP, OPC_BRANCH, OPC_STORE

def andi(rd, rs1, imm): return I(OPC_OPIMM, 7, rd, rs1, imm)
def sll(rd, rs1, rs2):  return R(OPC_OP, 1, 0, rd, rs1, rs2)
def or_(rd, rs1, rs2):  return R(OPC_OP, 6, 0, rd, rs1, rs2)
def add(rd, rs1, rs2):  return R(OPC_OP, 0, 0, rd, rs1, rs2)
def sb(rs2, rs1, imm):  return S(OPC_STORE, 0, rs1, rs2, imm)
def beq(rs1, rs2, imm): return B(OPC_BRANCH, 0, rs1, rs2, imm)
def jalr(rd, rs1, imm): return I(0x67, 0, rd, rs1, imm)

UART_DATA, UART_STAT = 0x0C, 0x10
PER, RAM, T, LEN, PTR, SUM, SH, A0, RA = 5, 6, 7, 8, 9, 11, 12, 10, 1

prog, notes, labels, fix = [], [], {}, []
def L(name): labels[name] = len(prog)
def emit(w, n): prog.append(w); notes.append(n)
def emit_to(fn, target, n):          # branch/jump resolved after layout
    fix.append((len(prog), fn, target)); emit(0, n)

emit(lui(PER, 0x30000),         "x5 = 0x3000_0000   peripherals")
emit(lui(RAM, 0x10000),         "x6 = 0x1000_0000   RAM A, where the program goes")
for ch in b"TP>":
    emit(addi(A0, 0, ch),       f"a0 = {chr(ch)!r}")
    emit_to(lambda off: jal(RA, off), "tx", "send it")
emit(addi(LEN, 0, 0),           "length = 0")
emit(addi(SH, 0, 0),            "shift = 0")
L("len")
emit_to(lambda off: jal(RA, off), "rx", "a0 = next byte")
emit(sll(A0, A0, SH),           "a0 <<= shift")
emit(or_(LEN, LEN, A0),         "length |= a0")
emit(addi(SH, SH, 8),           "shift += 8")
emit(addi(T, 0, 32),            "t = 32")
emit_to(lambda off: bne(SH, T, off), "len", "four bytes yet?")
emit(addi(PTR, RAM, 0),         "ptr = RAM")
emit(addi(SUM, 0, 0),           "sum = 0")
L("data")
emit_to(lambda off: beq(LEN, 0, off), "done", "all bytes in?")
emit_to(lambda off: jal(RA, off), "rx", "a0 = next byte")
emit(sb(A0, PTR, 0),            "store it")
emit(add(SUM, SUM, A0),         "sum += a0")
emit(addi(PTR, PTR, 1),         "ptr++")
emit(addi(LEN, LEN, -1),        "length--")
emit_to(lambda off: jal(0, off), "data", "loop")
L("done")
emit(addi(A0, SUM, 0),          "a0 = sum (the UART sends its low byte)")
emit_to(lambda off: jal(RA, off), "tx", "send the checksum")
emit(addi(A0, 0, ord("K")),     "a0 = 'K'")
emit_to(lambda off: jal(RA, off), "tx", "send it")
# Let 'K' finish leaving the wire before jumping: the loaded program may
# change UART_DIV in its first few instructions, and doing that mid-byte
# garbles the acknowledgement.
L("drain")
emit(lw(T, PER, UART_STAT),     "drain: t = UART_STAT")
emit(andi(T, T, 1),             "       t &= TX_BUSY")
emit_to(lambda off: bne(T, 0, off), "drain", "       wait for the last byte to leave")
emit(jalr(0, RAM, 0),           "run the program")
L("tx")
emit(lw(T, PER, UART_STAT),     "tx: t = UART_STAT")
emit(andi(T, T, 1),             "    t &= TX_BUSY")
emit_to(lambda off: bne(T, 0, off), "tx", "    wait while busy")
emit(sw(A0, PER, UART_DATA),    "    UART_DATA = a0")
emit(jalr(0, RA, 0),            "    return")
L("rx")
emit(lw(T, PER, UART_STAT),     "rx: t = UART_STAT")
emit(andi(T, T, 2),             "    t &= RX_VALID")
emit_to(lambda off: beq(T, 0, off), "rx", "    wait for a byte")
emit(lw(A0, PER, UART_DATA),    "    a0 = UART_DATA")
emit(jalr(0, RA, 0),            "    return")
for at, fn, target in fix:
    prog[at] = fn(4 * (labels[target] - at))

DEPTH = 64
assert len(prog) <= DEPTH, f"boot ROM overflows: {len(prog)} words"

rows = "\n".join(f"            6'd{i:<2}: data = 32'h{w:08x};   // {n}" for i, (w, n) in enumerate(zip(prog, notes)))
sv = f"""// tp_bootrom.sv — GENERATED by sw/mkboot.py. Do not edit; edit that and rerun it.
//
// The UART bootloader, {len(prog)} instructions, as a combinational table at
// 0x4000_0000. Hold ui_in[7] high while reset is released to run it. It
// prints "TP>", receives a length-prefixed program over the UART into RAM A,
// answers with a checksum and 'K', and jumps to 0x1000_0000.
//
// Synthesis turns the table into plain logic; there is no ROM macro.
`default_nettype none

module tp_bootrom (
    input  wire  logic [5:0]  addr,     // word address
    output logic       [31:0] data
);
    always_comb begin
        unique case (addr)
{rows}
            default: data = 32'h0000_0073;   // ECALL: halt if anything strays here
        endcase
    end
endmodule : tp_bootrom
"""
open("src/boot/tp_bootrom.sv", "w").write(sv)
for i, (w, n) in enumerate(zip(prog, notes)):
    print(f"{0x40000000 + 4*i:08x}: {w:08x}   {n}")
print(f"\n{len(prog)} of {DEPTH} words; wrote src/boot/tp_bootrom.sv")
