// tb_isa.sv — instruction set coverage. Runs a 168-instruction program that
// exercises every RV32I instruction TinyPulse implements and stores each result
// into the PSRAM, then checks all 49 results against sw/mkisa.py's
// independently-computed expectations.
//
// The expectation file is generated by Python doing the arithmetic in a
// completely different way from the hardware, which is the point: if both
// agree, they are unlikely to be wrong in the same direction.
//
// Run with:  make isa
`default_nettype none
`timescale 1ns/1ps

module tb_isa;

    localparam int TIMEOUT   = 4000000;
    localparam int MAX_SLOTS = 128;

    reg        clk   = 1'b0;
    reg        rst_n = 1'b0;
    reg        ena   = 1'b1;
    reg  [7:0] ui_in = 8'h00;

    wire [7:0] uo_out, uio_out, uio_oe;

    integer errors = 0;
    integer checks = 0;

    always #5 clk = ~clk;

    wire halt = uo_out[4];
    wire ill  = uo_out[5];
    wire sck  = uo_out[7];
    wire cs_f = uio_out[4];
    wire cs_r = uio_out[5];

    wire [3:0] flash_sd, psram_sd;
    wire [3:0] sd_bus = uio_oe[0] ? uio_out[3:0]
                      : (!cs_f ? flash_sd : (!cs_r ? psram_sd : 4'hF));
    wire [7:0] uio_in = {4'h0, sd_bus};

    tt_um_normansrule_tinypulse dut (
        .ui_in(ui_in), .uo_out(uo_out), .uio_in(uio_in),
        .uio_out(uio_out), .uio_oe(uio_oe),
        .ena(ena), .clk(clk), .rst_n(rst_n)
    );

    qspi_flash_model #(.DUMMY(4), .WORDS(512)) u_flash (
        .cs_n(cs_f), .sck(sck), .ctrl_sd(uio_out[3:0]), .dev_sd(flash_sd)
    );

    qspi_psram_model #(.DUMMY(6), .BYTES(4096)) u_psram (
        .cs_n(cs_r), .sck(sck), .ctrl_sd(uio_out[3:0]), .dev_sd(psram_sd)
    );

    // ---- expectations, read from the file the assembler wrote ----
    integer     exp_slot  [0:MAX_SLOTS-1];
    reg [31:0]  exp_value [0:MAX_SLOTS-1];
    reg [8*48:1] exp_label [0:MAX_SLOTS-1];
    integer     n_exp;

    integer fd, code, i, cyc;
    integer slot_i;
    reg [31:0] val_i;
    reg [8*48:1] lbl_i;
    reg [31:0] got;

    function [31:0] psram_word(input integer slot);
        begin
            psram_word = {u_psram.mem[slot*4 + 3], u_psram.mem[slot*4 + 2],
                          u_psram.mem[slot*4 + 1], u_psram.mem[slot*4 + 0]};
        end
    endfunction

    initial begin
        $dumpfile("tb_isa.vcd");
        $dumpvars(0, tb_isa);

        #1 $readmemh("isa.hex", u_flash.mem);

        n_exp = 0;
        fd = $fopen("isa_expect.txt", "r");
        if (fd == 0) begin
            $display("cannot open isa_expect.txt — run 'python3 ../sw/mkisa.py'");
            $finish;
        end
        code = 1;
        while (code > 0 && n_exp < MAX_SLOTS) begin
            code = $fscanf(fd, "%d %h %s\n", slot_i, val_i, lbl_i);
            if (code == 3) begin
                exp_slot[n_exp]  = slot_i;
                exp_value[n_exp] = val_i;
                exp_label[n_exp] = lbl_i;
                n_exp = n_exp + 1;
            end
        end
        $fclose(fd);

        $display("\n=== TinyPulse-Skywater130 instruction set coverage ===");
        $display("loaded %0d expected results", n_exp);

        repeat (20) @(posedge clk);
        rst_n = 1'b1;

        cyc = 0;
        while (!halt && cyc < TIMEOUT) begin
            @(posedge clk);
            cyc = cyc + 1;
        end

        $display("ran %0d clocks\n", cyc);

        checks = checks + 1;
        if (!halt) begin
            errors = errors + 1;
            $display("  FAIL  program never reached ECALL");
        end

        checks = checks + 1;
        if (ill) begin
            errors = errors + 1;
            $display("  FAIL  an illegal instruction was decoded");
        end

        for (i = 0; i < n_exp; i = i + 1) begin
            got = psram_word(exp_slot[i]);
            checks = checks + 1;
            if (got !== exp_value[i]) begin
                errors = errors + 1;
                $display("  FAIL  slot %0d  got %08x  want %08x   %0s",
                         exp_slot[i], got, exp_value[i], exp_label[i]);
            end
        end

        $display("\n%0d checks, %0d failures", checks, errors);
        if (errors == 0) $display("ISA COVERAGE PASSED\n");
        else             $display("ISA COVERAGE FAILED\n");
        $finish;
    end

endmodule
