# test.py — cocotb tests for TinyPulse-Skywater130.
#
# Output pins at reset (every pin in its built-in function):
#   uo_out[0] TRIG0   [1] TRIG1   [2] EVT   [3] OVF
#   uo_out[4] UART TX (idles HIGH)  [5] HALT   [6] ILLEGAL   [7] HEARTBEAT
#
# These drive the chip the way a board would: pins only, no hierarchy
# peeking except where a check genuinely needs the internal timebase. The
# program running underneath is test/prog.hex, generated by sw/mkprog.py.

# Positional time units rather than units=/unit=: the keyword was renamed
# in cocotb 2.0 and the positional form works on both 1.x and 2.x, which
# matters because continuous integration may pin either.
import os
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles, Timer

CLK_NS = 20          # 50 MHz

# After hardening the netlist has no u_soc / u_core / u_sync hierarchy, so the
# gate-level run (make GATES=yes, Tiny Tapeout's gl_test job) must use pins
# only. Tests that need an internal signal check this and fall back.
GL = os.environ.get("GATES") == "yes"


def bits(sig):
    return int(sig.value)


async def reset(dut, latency=0):
    """Hold reset. ui_in[2:0] sets the QSPI read latency while reset is low."""
    dut.ena.value = 1
    dut.ui_in.value = latency & 0x7
    dut.rst_n.value = 0
    await ClockCycles(dut.clk, 10)
    dut.rst_n.value = 1
    dut.ui_in.value = 0
    await RisingEdge(dut.clk)


@cocotb.test()
async def test_reset_state(dut):
    """After reset nothing is asserted and the queue is empty."""
    cocotb.start_soon(Clock(dut.clk, CLK_NS, "ns").start())
    await reset(dut)
    uo = bits(dut.uo_out)
    assert (uo & 0x01) == 0, "TRIG0 should be low after reset"
    assert (uo & 0x04) == 0, "EVT should be low: the queue starts empty"
    assert (uo & 0x08) == 0, "OVF should be low after reset"
    assert (uo & 0x20) == 0, "HALT should be low after reset"
    assert (uo & 0x40) == 0, "ILLEGAL should be low after reset"
    assert (uo & 0x10) != 0, "UART TX should idle high"


@cocotb.test(skip=GL)
async def test_timebase_runs(dut):
    """The timebase advances one tick per clock."""
    cocotb.start_soon(Clock(dut.clk, CLK_NS, "ns").start())
    await reset(dut)
    now = dut.user_project.u_soc.u_sync.now
    a = int(now.value)
    await ClockCycles(dut.clk, 100)
    b = int(now.value)
    assert b - a == 100, f"timebase moved {b - a} ticks in 100 clocks"


@cocotb.test()
async def test_capture_event(dut):
    """An edge on a capture pin queues a timestamped event."""
    cocotb.start_soon(Clock(dut.clk, CLK_NS, "ns").start())
    await reset(dut)

    # let the program run far enough to have written the capture config
    await ClockCycles(dut.clk, 400)

    dut.ui_in.value = 0x08          # CAP3 high
    await ClockCycles(dut.clk, 10)
    dut.ui_in.value = 0x00
    await ClockCycles(dut.clk, 10)

    assert bits(dut.uo_out) & 0x04, "EVT should be high after a capture edge"


@cocotb.test()
async def test_program_runs_to_halt(dut):
    """The self-test program arms a deadline, waits on it, and halts."""
    cocotb.start_soon(Clock(dut.clk, CLK_NS, "ns").start())
    await reset(dut)

    if GL:
        # no internal state to watch: start observing TRIG0 right away,
        # since the deadline can land within a few hundred clocks of reset
        core, now = None, None
    else:
        core = dut.user_project.u_soc.g_cpu.u_core
        now = dut.user_project.u_soc.u_sync.now
        # wait until the core parks in TWAIT (state 3)
        for _ in range(20000):
            await RisingEdge(dut.clk)
            if int(core.state.value) == 3:
                break
        else:
            assert False, "core never reached TWAIT"

    # produce a hardware capture edge while it is parked
    await ClockCycles(dut.clk, 20)
    dut.ui_in.value = 0x02          # CAP1
    await ClockCycles(dut.clk, 20)
    dut.ui_in.value = 0x00

    # catch the trigger edge and the tick it happened on
    trig_tick = None
    prev = 0
    halted = False
    for _ in range(40000):
        await RisingEdge(dut.clk)
        await Timer(1, "ns")
        uo = bits(dut.uo_out)
        if (uo & 0x01) and not prev and trig_tick is None:
            trig_tick = int(now.value) if now is not None else -1
        prev = uo & 0x01
        if uo & 0x20:                 # uo_out[5] = HALT
            halted = True
            break

    assert halted, "core never halted"
    assert trig_tick is not None, "TRIG0 never fired"
    assert not (bits(dut.uo_out) & 0x40), "an illegal instruction was decoded"
    assert not (bits(dut.uo_out) & 0x08), "the event queue overflowed"

    if GL:
        return          # tick-exact checks need the internal timebase
    # the program stored t0 at PSRAM word 0; the deadline was t0 + 400
    mem = dut.u_psram.mem
    t0 = (int(mem[3].value) << 24) | (int(mem[2].value) << 16) | \
         (int(mem[1].value) << 8) | int(mem[0].value)
    assert trig_tick == t0 + 400, \
        f"trigger fired at tick {trig_tick}, programmed for {t0 + 400}"

    ev = (int(mem[7].value) << 24) | (int(mem[6].value) << 16) | \
         (int(mem[5].value) << 8) | int(mem[4].value)
    assert (ev >> 31) == 0, "event should be a hardware capture"
    assert ((ev >> 28) & 7) == 1, "event should be on channel CAP1"
    assert ((ev >> 27) & 1) == 1, "event should be a rising edge"


@cocotb.test()
async def test_hello_uart_and_gpio(dut):
    """The microcontroller test: firmware prints over the UART, echoes the
    input pins to the output pins, and blinks one with GPIO_XOR. Everything is
    checked from the pins, the way a PC on the other end of the RP2040 sees it."""
    cocotb.start_soon(Clock(dut.clk, CLK_NS, "ns").start())

    # load the hello firmware into the flash model in place of prog.hex
    with open("hello.hex") as f:
        words = [int(l, 16) for l in f if l.strip()]
    for i, w in enumerate(words):
        dut.u_flash.mem[i].value = w
    await reset(dut)
    PATTERN = 0x5A                   # bit 3 (UART RX) high = idle line
    dut.ui_in.value = PATTERN

    core = None if GL else dut.user_project.u_soc.g_cpu.u_core
    DIV = 8                          # the firmware sets 8 clocks per bit

    async def uart_byte():
        # wait for a start bit on uo_out[4], then sample mid-bit
        while True:
            await RisingEdge(dut.clk)
            if not (bits(dut.uo_out) >> 4) & 1:
                break
        await ClockCycles(dut.clk, DIV // 2)
        assert not (bits(dut.uo_out) >> 4) & 1, "start bit did not hold"
        value = 0
        for i in range(8):
            await ClockCycles(dut.clk, DIV)
            value |= ((bits(dut.uo_out) >> 4) & 1) << i
        await ClockCycles(dut.clk, DIV)
        assert (bits(dut.uo_out) >> 4) & 1, "stop bit missing"
        return value

    text = bytearray()
    for _ in range(len(b"Hi TinyPulse\n")):
        text.append(await uart_byte())
    dut._log.info(f"UART said: {bytes(text)!r}")
    assert bytes(text) == b"Hi TinyPulse\n", f"got {bytes(text)!r}"

    # after the message: echo, then three toggles of bit 7, then ECALL
    toggles, prev7 = 0, None
    for _ in range(20000):
        await RisingEdge(dut.clk)
        b7 = (bits(dut.uo_out) >> 7) & 1
        if prev7 is not None and b7 != prev7:
            toggles += 1
        prev7 = b7
        if core is not None and int(core.halted.value):
            break
        if core is None and toggles >= 3:
            await ClockCycles(dut.clk, 200)
            break
    else:
        assert False, "firmware never reached ECALL"

    await ClockCycles(dut.clk, 2)
    uo = bits(dut.uo_out)
    want = (PATTERN ^ 0x80)
    assert (uo & 0xEF) == (want & 0xEF), \
        f"GPIO echo: uo_out = {uo:#04x}, expected {want & 0xEF:#04x} on the GPIO pins"
    assert toggles >= 3, f"uo_out[7] toggled {toggles} times, expected the 3 XOR writes"


@cocotb.test()
async def test_boot_strap_starts_bootloader(dut):
    """Hold ui_in[7] high through reset: the boot ROM runs and prints "TP>" at
    the reset baud rate (434 clocks per bit, 115,200 baud at 50 MHz). Pins
    only, so this also proves the boot ROM in the gate-level netlist."""
    cocotb.start_soon(Clock(dut.clk, CLK_NS, "ns").start())
    dut.ena.value = 1
    dut.ui_in.value = 0x88           # ui[7] boot strap, ui[3] UART RX idle high
    dut.rst_n.value = 0
    await ClockCycles(dut.clk, 10)
    dut.rst_n.value = 1
    DIV = 434
    got = bytearray()
    for _ in range(3):
        for _ in range(200000):
            await RisingEdge(dut.clk)
            if not (bits(dut.uo_out) >> 4) & 1:
                break
        else:
            assert False, f"no start bit; received {bytes(got)!r} so far"
        await ClockCycles(dut.clk, DIV // 2)
        v = 0
        for i in range(8):
            await ClockCycles(dut.clk, DIV)
            v |= ((bits(dut.uo_out) >> 4) & 1) << i
        await ClockCycles(dut.clk, DIV)
        got.append(v)
    dut._log.info(f"boot ROM said: {bytes(got)!r}")
    assert bytes(got) == b"TP>", f"expected TP>, got {bytes(got)!r}"
