# test.py — cocotb tests for TinyPulse-Skywater130.
#
# These drive the chip the way a board would: pins only, no hierarchy
# peeking except where a check genuinely needs the internal timebase. The
# program running underneath is test/prog.hex, generated by sw/mkprog.py.

# Positional time units rather than units=/unit=: the keyword was renamed
# in cocotb 2.0 and the positional form works on both 1.x and 2.x, which
# matters because continuous integration may pin either.
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles, Timer

CLK_NS = 20          # 50 MHz


def bits(sig):
    return int(sig.value)


async def reset(dut, latency=0):
    """Hold reset. ui_in[2:0] sets the QSPI read latency while reset is low."""
    dut.ena.value = 1
    dut.ui_in.value = latency & 0x7
    dut.rst_n.value = 0
    await ClockCycles(dut.clk, 10)
    dut.rst_n.value = 1
    dut.ui_in.value = 0
    await RisingEdge(dut.clk)


@cocotb.test()
async def test_reset_state(dut):
    """After reset nothing is asserted and the queue is empty."""
    cocotb.start_soon(Clock(dut.clk, CLK_NS, "ns").start())
    await reset(dut)
    uo = bits(dut.uo_out)
    assert (uo & 0x01) == 0, "TRIG0 should be low after reset"
    assert (uo & 0x04) == 0, "EVT should be low: the queue starts empty"
    assert (uo & 0x08) == 0, "OVF should be low after reset"
    assert (uo & 0x20) == 0, "ILL should be low after reset"


@cocotb.test()
async def test_timebase_runs(dut):
    """The timebase advances one tick per clock."""
    cocotb.start_soon(Clock(dut.clk, CLK_NS, "ns").start())
    await reset(dut)
    now = dut.user_project.u_soc.u_sync.now
    a = int(now.value)
    await ClockCycles(dut.clk, 100)
    b = int(now.value)
    assert b - a == 100, f"timebase moved {b - a} ticks in 100 clocks"


@cocotb.test()
async def test_capture_event(dut):
    """An edge on a capture pin queues a timestamped event."""
    cocotb.start_soon(Clock(dut.clk, CLK_NS, "ns").start())
    await reset(dut)

    # let the program run far enough to have written the capture config
    await ClockCycles(dut.clk, 400)

    dut.ui_in.value = 0x08          # CAP3 high
    await ClockCycles(dut.clk, 10)
    dut.ui_in.value = 0x00
    await ClockCycles(dut.clk, 10)

    assert bits(dut.uo_out) & 0x04, "EVT should be high after a capture edge"


@cocotb.test()
async def test_program_runs_to_halt(dut):
    """The self-test program arms a deadline, waits on it, and halts."""
    cocotb.start_soon(Clock(dut.clk, CLK_NS, "ns").start())
    await reset(dut)

    core = dut.user_project.u_soc.g_cpu.u_core
    now = dut.user_project.u_soc.u_sync.now

    # wait until the core parks in TWAIT (EX_WAIT == 3)
    for _ in range(20000):
        await RisingEdge(dut.clk)
        if int(core.state.value) == 3:
            break
    else:
        assert False, "core never reached TWAIT"

    # produce a hardware capture edge while it is parked
    await ClockCycles(dut.clk, 20)
    dut.ui_in.value = 0x02          # CAP1
    await ClockCycles(dut.clk, 20)
    dut.ui_in.value = 0x00

    # catch the trigger edge and the tick it happened on
    trig_tick = None
    prev = 0
    halted = False
    for _ in range(40000):
        await RisingEdge(dut.clk)
        await Timer(1, "ns")
        uo = bits(dut.uo_out)
        if (uo & 0x01) and not prev and trig_tick is None:
            trig_tick = int(now.value)
        prev = uo & 0x01
        if uo & 0x10:
            halted = True
            break

    assert halted, "core never halted"
    assert trig_tick is not None, "TRIG0 never fired"
    assert not (bits(dut.uo_out) & 0x20), "an illegal instruction was decoded"
    assert not (bits(dut.uo_out) & 0x08), "the event queue overflowed"

    # the program stored t0 at PSRAM word 0; the deadline was t0 + 400
    mem = dut.u_psram.mem
    t0 = (int(mem[3].value) << 24) | (int(mem[2].value) << 16) | \
         (int(mem[1].value) << 8) | int(mem[0].value)
    assert trig_tick == t0 + 400, \
        f"trigger fired at tick {trig_tick}, programmed for {t0 + 400}"

    ev = (int(mem[7].value) << 24) | (int(mem[6].value) << 16) | \
         (int(mem[5].value) << 8) | int(mem[4].value)
    assert (ev >> 31) == 0, "event should be a hardware capture"
    assert ((ev >> 28) & 7) == 1, "event should be on channel CAP1"
    assert ((ev >> 27) & 1) == 1, "event should be a rising edge"
