#!/usr/bin/env python3
"""run_act.py — the official RISC-V architecture tests for RV32E, on TinyPulse.

Source: github.com/riscv-non-isa/riscv-arch-test, branch old-framework-2.x,
riscv-test-suite/rv32e_unratified/E: 37 tests, one per RV32E base
instruction, each with a reference signature generated by the RISC-V golden
model. Each test is assembled with Clang, checked with sw/rv32e_check.py, run
on the RTL, and its signature compared word for word with the reference.

    python3 act/run_act.py [TESTDIR] [test ...]      (from test/)

TESTDIR defaults to act/riscv-arch-test (fetch it with act/fetch.sh).
"""
import os, shutil, subprocess, sys, time
from elftools.elf.elffile import ELFFile

HERE = os.path.dirname(os.path.abspath(__file__))
TEST = os.path.dirname(HERE)
root = sys.argv[1] if len(sys.argv) > 1 and os.path.isdir(sys.argv[1]) else os.path.join(HERE, "riscv-arch-test")
only = [a for a in sys.argv[1:] if not os.path.isdir(a)]
SUITE = os.path.join(root, "riscv-test-suite")
SRC = os.path.join(SUITE, "rv32e_unratified", "E", "src")
REF = os.path.join(SUITE, "rv32e_unratified", "E", "references")
if not os.path.isdir(SRC):
    sys.exit(f"no tests at {SRC}: run act/fetch.sh first")

# every test compiles from scratch: a private cache, wiped per test (see test/Makefile)
ZIG_CACHE = os.path.join(TEST, ".zig-cache-act")
os.environ["ZIG_GLOBAL_CACHE_DIR"] = os.environ["ZIG_LOCAL_CACHE_DIR"] = ZIG_CACHE
CC = [sys.executable, "-m", "ziglang", "cc", "-target", "riscv32-freestanding-none",
      "-mcpu=generic_rv32+e-i", "-mabi=ilp32e", "-nostdlib", "-g", "-DXLEN=32", "-DRVTEST_E=True",
      "-Wno-macro-redefined", "-I", HERE, "-I", os.path.join(SUITE, "env"),
      "-T", os.path.join(HERE, "link_act.ld"), "-Wl,-e,rvtest_entry_point"]
BASE = 0x10000000

rtl = []
for line in open(os.path.join(TEST, "Makefile")):
    if line.startswith("RTL"):
        rtl.append(line.split("=", 1)[1].strip().replace("$(SRC)", "../src"))
subprocess.run(["iverilog", "-g2012", "-o", "tb_act.vvp", "-s", "tb_act", *rtl, "qspi_model.sv", "tb_act.sv"],
               cwd=TEST, check=True, stderr=subprocess.DEVNULL)

tests = sorted(f[:-2] for f in os.listdir(SRC) if f.endswith(".S"))
if only: tests = [t for t in tests if t in only]
passed, failed, t_start = 0, [], time.time()
for t in tests:
    shutil.rmtree(ZIG_CACHE, ignore_errors=True)
    elf = os.path.join(TEST, "act_test.elf")
    r = subprocess.run(CC + ["-o", elf, os.path.join(SRC, t + ".S")], capture_output=True, text=True)
    if r.returncode:
        print(f"  FAIL  {t:<16} does not assemble\n{r.stderr[-800:]}"); failed.append(t); continue
    chk = subprocess.run([sys.executable, os.path.join(TEST, "..", "sw", "rv32e_check.py"), elf],
                         capture_output=True, text=True)
    e = ELFFile(open(elf, "rb"))
    syms = {s.name: s["st_value"] for s in e.get_section_by_name(".symtab").iter_symbols()}
    image = bytearray()
    for seg in e.iter_segments():
        if seg["p_type"] == "PT_LOAD" and seg["p_filesz"]:
            off = seg["p_paddr"] - BASE
            image[len(image):off + seg["p_filesz"]] = b"\0" * max(0, off + seg["p_filesz"] - len(image))
            image[off:off + seg["p_filesz"]] = seg.data()
    HALF = 1 << 23                                    # RAM A, then RAM B
    with open(os.path.join(TEST, "act_image.hex"), "w") as f:
        f.write("\n".join(f"{b:02x}" for b in image[:HALF]))
    extra = []
    if len(image) > HALF:
        with open(os.path.join(TEST, "act_image_b.hex"), "w") as f:
            f.write("\n".join(f"{b:02x}" for b in image[HALF:]))
        extra = ["+RAMB"]
    sb, se = syms["begin_signature"] - BASE, syms["end_signature"] - BASE
    run = subprocess.run(["vvp", "-n", "tb_act.vvp", f"+SIG_BEGIN={sb}", f"+SIG_END={se}", *extra],
                         cwd=TEST, capture_output=True, text=True)
    status = next((l for l in run.stdout.splitlines() if l.startswith("ACT ")), "ACT no result")
    got = [l.strip().lower() for l in open(os.path.join(TEST, "act_signature.txt")) if l.strip()]
    want = [l.strip().lower() for l in open(os.path.join(REF, t + ".reference_output")) if l.strip()]
    ok = got == want and "halted=1" in status and "ramtiming=0" in status and chk.returncode == 0
    if ok:
        passed += 1
        print(f"  ok    {t:<16} {len(want):4d} signature words match   ({status.split()[-1]})")
    else:
        failed.append(t)
        first = next((i for i, (g, w) in enumerate(zip(got, want)) if g != w), min(len(got), len(want)))
        print(f"  FAIL  {t:<16} {status}; {len(got)} vs {len(want)} words; first difference at word {first}"
              + (f": got {got[first]} want {want[first]}" if first < min(len(got), len(want)) else ""))
shutil.rmtree(ZIG_CACHE, ignore_errors=True)
for f in ("act_test.elf", "act_image.hex", "act_image_b.hex", "act_signature.txt", "tb_act.vvp"):
    try: os.remove(os.path.join(TEST, f))
    except OSError: pass
print(f"\n{passed} of {len(tests)} official RV32E tests pass ({time.time() - t_start:.0f} s)")
print("ARCH TESTS PASSED" if not failed else "ARCH TESTS FAILED: " + " ".join(failed))
sys.exit(1 if failed else 0)
