// tp_bootrom.sv — GENERATED by sw/mkboot.py. Do not edit; edit that and rerun it.
//
// The UART bootloader, 43 instructions, as a combinational table at
// 0x4000_0000. Hold ui_in[7] high while reset is released to run it. It
// prints "TP>", receives a length-prefixed program over the UART into RAM A,
// answers with a checksum and 'K', and jumps to 0x1000_0000.
//
// Synthesis turns the table into plain logic; there is no ROM macro.
`default_nettype none

module tp_bootrom (
    input  wire  logic [5:0]  addr,     // word address
    output logic       [31:0] data
);
    always_comb begin
        unique case (addr)
            6'd0 : data = 32'h300002b7;   // x5 = 0x3000_0000   peripherals
            6'd1 : data = 32'h10000337;   // x6 = 0x1000_0000   RAM A, where the program goes
            6'd2 : data = 32'h05400513;   // a0 = 'T'
            6'd3 : data = 32'h078000ef;   // send it
            6'd4 : data = 32'h05000513;   // a0 = 'P'
            6'd5 : data = 32'h070000ef;   // send it
            6'd6 : data = 32'h03e00513;   // a0 = '>'
            6'd7 : data = 32'h068000ef;   // send it
            6'd8 : data = 32'h00000413;   // length = 0
            6'd9 : data = 32'h00000613;   // shift = 0
            6'd10: data = 32'h070000ef;   // a0 = next byte
            6'd11: data = 32'h00c51533;   // a0 <<= shift
            6'd12: data = 32'h00a46433;   // length |= a0
            6'd13: data = 32'h00860613;   // shift += 8
            6'd14: data = 32'h02000393;   // t = 32
            6'd15: data = 32'hfe7616e3;   // four bytes yet?
            6'd16: data = 32'h00030493;   // ptr = RAM
            6'd17: data = 32'h00000593;   // sum = 0
            6'd18: data = 32'h00040e63;   // all bytes in?
            6'd19: data = 32'h04c000ef;   // a0 = next byte
            6'd20: data = 32'h00a48023;   // store it
            6'd21: data = 32'h00a585b3;   // sum += a0
            6'd22: data = 32'h00148493;   // ptr++
            6'd23: data = 32'hfff40413;   // length--
            6'd24: data = 32'hfe9ff06f;   // loop
            6'd25: data = 32'h00058513;   // a0 = sum (the UART sends its low byte)
            6'd26: data = 32'h01c000ef;   // send the checksum
            6'd27: data = 32'h04b00513;   // a0 = 'K'
            6'd28: data = 32'h014000ef;   // send it
            6'd29: data = 32'h0102a383;   // drain: t = UART_STAT
            6'd30: data = 32'h0013f393;   //        t &= TX_BUSY
            6'd31: data = 32'hfe039ce3;   //        wait for the last byte to leave
            6'd32: data = 32'h00030067;   // run the program
            6'd33: data = 32'h0102a383;   // tx: t = UART_STAT
            6'd34: data = 32'h0013f393;   //     t &= TX_BUSY
            6'd35: data = 32'hfe039ce3;   //     wait while busy
            6'd36: data = 32'h00a2a623;   //     UART_DATA = a0
            6'd37: data = 32'h00008067;   //     return
            6'd38: data = 32'h0102a383;   // rx: t = UART_STAT
            6'd39: data = 32'h0023f393;   //     t &= RX_VALID
            6'd40: data = 32'hfe038ce3;   //     wait for a byte
            6'd41: data = 32'h00c2a503;   //     a0 = UART_DATA
            6'd42: data = 32'h00008067;   //     return
            default: data = 32'h0000_0073;   // ECALL: halt if anything strays here
        endcase
    end
endmodule : tp_bootrom
